# Generated by Django 4.1a1 on 2022-11-18 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anio',
            fields=[
                ('id_anio', models.BigAutoField(primary_key=True, serialize=False)),
                ('valor_anio', models.BigIntegerField()),
            ],
            options={
                'db_table': 'anio',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Eje',
            fields=[
                ('id_eje', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion_eje', models.CharField(blank=True, max_length=500, null=True)),
                ('fecha_creacion_eje', models.DateField()),
                ('nombre_eje', models.CharField(max_length=300)),
                ('usuario_creacion_eje', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'eje',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Financiamiento',
            fields=[
                ('id_financiamiento', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_financiamiento', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'financiamiento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id_indicador', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_indicador', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'indicador',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Mes',
            fields=[
                ('id_mes', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_mes', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'mes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id_organizacion', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_organizacion', models.CharField(max_length=500, verbose_name='Nombre')),
                ('descripcion_organizacion', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descripción')),
                ('mision_organizacion', models.CharField(blank=True, max_length=500, null=True, verbose_name='Misión')),
                ('vision_organizacion', models.CharField(blank=True, max_length=500, null=True, verbose_name='Visión')),
            ],
            options={
                'verbose_name': 'Organización',
                'verbose_name_plural': 'Organizaciones',
                'db_table': 'organizacion',
                'ordering': ['descripcion_organizacion'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id_periodo', models.BigAutoField(primary_key=True, serialize=False)),
                ('anio_fin', models.BigIntegerField()),
                ('anio_inicio', models.BigIntegerField()),
                ('nombre_periodo', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'periodo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoIndicador',
            fields=[
                ('id_tipo_indicador', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_indicador', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'tipo_indicador',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoObjetivo',
            fields=[
                ('id_tipo_objetivo', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_objetivo', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'tipo_objetivo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoPlan',
            fields=[
                ('id_tipo_plan', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_tipo_plan', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'tipo_plan',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id_unidad_medida', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_unidad_medida', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'unidad_medida',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UnidadPresupuestaria',
            fields=[
                ('id_unidad_presupuestaria', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_unidad_presupuestaria', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'unidad_presupuestaria',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UnidadOrganizativa',
            fields=[
                ('id_unidad_organizativa', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Unidad organizativa')),
                ('nombre_unidad_organizativa', models.CharField(max_length=500, verbose_name='Nombre unidad organizativa')),
                ('organizacion', models.ForeignKey(db_column='id_organizacion', on_delete=django.db.models.deletion.RESTRICT, to='siplan.organizacion', verbose_name='Organización')),
                ('unidad_superior', models.ForeignKey(blank=True, db_column='id_unidad_superior', null=True, on_delete=django.db.models.deletion.RESTRICT, to='siplan.unidadorganizativa', verbose_name='Unidad superior')),
            ],
            options={
                'verbose_name': 'Unidad organizativa',
                'verbose_name_plural': 'Unidades organizativas',
                'db_table': 'unidad_organizativa',
                'ordering': ['nombre_unidad_organizativa'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id_resultado', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion_resultado', models.CharField(blank=True, max_length=500, null=True)),
                ('fecha_creacion_resultado', models.DateField(blank=True, null=True)),
                ('nombre_responsable_resultado', models.CharField(blank=True, max_length=500, null=True)),
                ('nombre_resultado', models.CharField(max_length=500)),
                ('usuario_creacion_resultado', models.CharField(max_length=300)),
                ('id_eje', models.ForeignKey(db_column='id_eje', on_delete=django.db.models.deletion.RESTRICT, to='siplan.eje')),
                ('id_indicador', models.ForeignKey(db_column='id_indicador', on_delete=django.db.models.deletion.RESTRICT, to='siplan.indicador')),
            ],
            options={
                'db_table': 'resultado',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id_plan', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion_plan', models.CharField(max_length=500)),
                ('fecha_creacion_plan', models.DateField()),
                ('nombre_plan', models.CharField(max_length=300)),
                ('usuario_creacion_plan', models.CharField(max_length=300)),
                ('id_tipo_plan', models.ForeignKey(db_column='id_tipo_plan', on_delete=django.db.models.deletion.RESTRICT, to='siplan.tipoplan')),
            ],
            options={
                'db_table': 'plan',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('id_objetivo', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion_objetivo', models.CharField(blank=True, max_length=500, null=True)),
                ('fecha_creacion_objetivo', models.DateField()),
                ('nombre_objetivo', models.CharField(max_length=300)),
                ('usuario_creacion_objetivo', models.CharField(max_length=300)),
                ('id_organizacion', models.ForeignKey(db_column='id_organizacion', on_delete=django.db.models.deletion.RESTRICT, to='siplan.organizacion')),
                ('id_tipo_objetivo', models.ForeignKey(db_column='id_tipo_objetivo', on_delete=django.db.models.deletion.RESTRICT, to='siplan.tipoobjetivo')),
            ],
            options={
                'db_table': 'objetivo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LineaTrabajo',
            fields=[
                ('id_linea_trabajo', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_linea_trabajo', models.CharField(max_length=300)),
                ('id_unidad_presupuestaria', models.ForeignKey(db_column='id_unidad_presupuestaria', on_delete=django.db.models.deletion.RESTRICT, to='siplan.unidadpresupuestaria')),
            ],
            options={
                'db_table': 'linea_trabajo',
                'managed': True,
                'unique_together': {('id_linea_trabajo', 'id_unidad_presupuestaria')},
            },
        ),
        migrations.AddField(
            model_name='indicador',
            name='id_tipo_indicador',
            field=models.ForeignKey(db_column='id_tipo_indicador', on_delete=django.db.models.deletion.RESTRICT, to='siplan.tipoindicador'),
        ),
        migrations.AddField(
            model_name='indicador',
            name='id_unidad_medida',
            field=models.ForeignKey(db_column='id_unidad_medida', on_delete=django.db.models.deletion.RESTRICT, to='siplan.unidadmedida'),
        ),
        migrations.AddField(
            model_name='eje',
            name='id_objetivo',
            field=models.ForeignKey(db_column='id_objetivo', on_delete=django.db.models.deletion.RESTRICT, to='siplan.objetivo'),
        ),
        migrations.CreateModel(
            name='AnioResultado',
            fields=[
                ('id_anio_resultado', models.BigAutoField(primary_key=True, serialize=False)),
                ('activo', models.BooleanField()),
                ('id_anio', models.ForeignKey(db_column='id_anio', on_delete=django.db.models.deletion.RESTRICT, to='siplan.anio')),
                ('id_resultado', models.ForeignKey(db_column='id_resultado', on_delete=django.db.models.deletion.RESTRICT, to='siplan.resultado')),
            ],
            options={
                'db_table': 'anio_resultado',
                'managed': True,
                'unique_together': {('id_anio', 'id_resultado')},
            },
        ),
        migrations.AddField(
            model_name='anio',
            name='id_periodo',
            field=models.ForeignKey(db_column='id_periodo', on_delete=django.db.models.deletion.RESTRICT, to='siplan.periodo'),
        ),
        migrations.CreateModel(
            name='Accion',
            fields=[
                ('id_accion', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion_accion', models.CharField(blank=True, max_length=500, null=True)),
                ('fecha_creacion_accion', models.DateField(blank=True, null=True)),
                ('nombre_accion', models.CharField(max_length=300)),
                ('nombre_responsable_accion', models.CharField(blank=True, max_length=500, null=True)),
                ('numero_acciones_anuales_accion', models.IntegerField()),
                ('observacion', models.CharField(blank=True, max_length=500, null=True)),
                ('presupuesto_asignado_accion', models.FloatField(blank=True, null=True)),
                ('usuario_creacion_accion', models.CharField(max_length=300)),
                ('id_anio_resultado', models.ForeignKey(db_column='id_anio_resultado', on_delete=django.db.models.deletion.RESTRICT, to='siplan.anioresultado')),
                ('id_financiamiento', models.ForeignKey(db_column='id_financiamiento', on_delete=django.db.models.deletion.RESTRICT, to='siplan.financiamiento')),
                ('id_linea_trabajo', models.ForeignKey(db_column='id_linea_trabajo', on_delete=django.db.models.deletion.RESTRICT, to='siplan.lineatrabajo')),
            ],
            options={
                'db_table': 'accion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id_seguimiento', models.AutoField(primary_key=True, serialize=False)),
                ('detalle_seguimiento', models.CharField(max_length=500)),
                ('ejecutado', models.BooleanField(blank=True, null=True)),
                ('fecha_creacion_seguimiento', models.DateField()),
                ('fecha_edicion_seguimiento', models.DateField(blank=True, null=True)),
                ('fecha_ejecucion_seguimiento', models.DateField(blank=True, null=True)),
                ('numero_acciones_mensuales', models.BigIntegerField()),
                ('presupuesto_ejecutado', models.FloatField()),
                ('usuario_creacion_seguimiento', models.CharField(max_length=300)),
                ('usuario_edicion_seguimiento', models.CharField(blank=True, max_length=300, null=True)),
                ('id_accion', models.ForeignKey(db_column='id_accion', on_delete=django.db.models.deletion.RESTRICT, to='siplan.accion')),
                ('id_mes', models.ForeignKey(db_column='id_mes', on_delete=django.db.models.deletion.RESTRICT, to='siplan.mes')),
            ],
            options={
                'db_table': 'seguimiento',
                'managed': True,
                'unique_together': {('id_accion', 'id_mes')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='anio',
            unique_together={('id_anio', 'id_periodo')},
        ),
    ]
